### ISSUE TITLE
Don't generate keys for root

### ISSUE THREAD

**Issue by jabl** [CSC-IT-Center-for-Science/ansible-role-fgci-bash#2]
In createkeys.{sh.csh} keys should not be generated for root. As /root is local to each node, there's not much point in generating a key and putting it in the authorized_keys.

**Comment by martbhell** [comment]
Agreed. Changed in a206fd51bc0755daec1839d92706c1299da320da and cd0432cc33ecfd4eabad77237c5347bbc30aaf20
