### ISSUE TITLE
Generate ed25519 keys instead of rsa

### ISSUE THREAD

**Issue by jabl** [CSC-IT-Center-for-Science/ansible-role-fgci-bash#3]
When generating a passwordless key the first time one logs in, since the entire cluster is running EL7, we might as well use ed25519 keys instead of rsa.

**Comment by martbhell** [comment]
618aebf1f5fdd36d27afd4b4c1add07263f3a9f1 and 0cd8d8cb14c92806e079a66636c5f8089b0edff3 changes to ed25519. Existing authorized_keys or keys themselves are not overwritten by this change so should be fairly safe.

Thanks!
